#config_version=5
#This version is 
mode:
  start_events: round2end
  stop_events: end_game
  priority: 500
  events_when_started:
      - disableAutofire #disables the slingshots and flippers
      - disable_p1_flipper
      - disable_single_player
      - disable_double_player
      - enable_front_lock
      - enable_back_lock
      - tally_scores 
      - start_round2end_timer

event_player:  
#This is to end the round when the troughs are full
    balldevice_bd_trough_back_ball_count_changed{balls==2 and device.ball_devices.bd_trough_front.balls==2}: #trigger when there is 2 balls in front trough and 2 in back 
      - balls_ballanced_end #start_round2end_timer
    balldevice_bd_trough_front_ball_count_changed{balls==2 and device.ball_devices.bd_trough_back.balls==2}: #trigger when there is 2 balls in front trough and 2 in back 
      - balls_ballanced_end #start_round2end_timer  
    timer_round2end_timer_complete: start_mode_egg_bonus_tally
#    timer_round2end_timer_complete: autobalance_complete #this ends the game - see game: on config file
    timer_end_timer_complete: #end_game
      - reset_droptargets
      - end_game

timers:
    round2end_timer: 
        start_value: 3
        end_value: 0
        direction: down
        control_events:
            - event: start_round2end_timer
              action: start 
    end_timer: 
        start_value: 6
        end_value: 0
        direction: down
        control_events:
            - event: start_end_timer
              action: start 
variable_player:
    timer_round2end_timer_tick: 
        timer_round2end_timer_variable:
            int: ticks
            action: set
    tally_scores: 
        p1_prebonus_score:
            int: current_player.p1_score
            action: set
        p1_total_egg_bonus:
            int: current_player.p1_egg_bonus
            action: set
        p1_postbonus_score:
            int: current_player.p1_prebonus_score + (current_player.p1_total_egg_bonus * current_player.p1_total_multiplier * 1000)
            action: set
        p2_prebonus_score:
            int: current_player.p2_score
            action: set
        p2_total_egg_bonus:
            int: current_player.p2_egg_bonus
            action: set
        p2_postbonus_score:
            int: current_player.p2_prebonus_score + (current_player.p2_total_egg_bonus * current_player.p2_total_multiplier * 1000)
            action: set
        p1_score:
            int: current_player.p1_postbonus_score
            action: set_machine
        p2_score:
            int: current_player.p2_postbonus_score
            action: set_machine
        total_score:
            int: current_player.p1_postbonus_score + current_player.p2_postbonus_score
            action: set_machine
show_player:
    mode_round2end_started:
        quickflashColor:
            speed: 1
            show_tokens:
                color: red
                led: l_p1_game over, l_p2_game over    
accruals:
  end_game_accrual:
    events:
      - balls_ballanced_end
      - egg_bonus_tally_complete
    events_when_complete: start_end_timer
    
