#config_version=5
mode:
  start_events: start_mode_unlimited_multiball 
  priority: 401
  events_when_started:
      - enableAutofire
      - enable_unlimited_mulitiball 
      - start_front_unlimited_multiball
      - start_back_unlimited_multiball
      - eject_all #this is needed because for some reason after the first game - will not eject balls 
event_player:
    timer_unlimited_multiball_complete:
      - round2end
 
timers:
    unlimited_multiball:
        start_value: 30
        end_value: 0
        direction: down
        control_events:
            - event: mode_unlimited_multiball_started
              action: start
            - event: p1_disap_t_roll_hit
              action: restart
            - event: p2_disap_t_roll_hit
              action: restart

variable_player:
    timer_unlimited_multiball_tick:
        timer_unlimited_multiball_variable:
            int: ticks
            action: set
    round2end:
        timer_unlimited_multiball_variable:    
            int: 0
            action: set #not sure why this is not working and the timer ends on 1
multiballs:
    p1_unlimited:
        ball_count: 2
        ball_count_type: add
        ball_locks: bd_trough_back
        enable_events: enable_unlimited_mulitiball 
        start_events: start_back_unlimited_multiball 
        stop_events: round2end
        shoot_again: 2d      
    p2_unlimited:
        ball_count: 2
        ball_count_type: add
        ball_locks: bd_trough_front
        enable_events: enable_unlimited_mulitiball 
        start_events: start_front_unlimited_multiball
        stop_events: round2end
        shoot_again: 2d
                  
shows:
    multiball_flash:
        - duration: 200ms
          lights:
              (led): (color)
        - duration: 100ms
          lights:
              (led): off    
    multiball_off:
        - time: 0
          lights:
              (led): tt_white
              (ledoff): black   
show_player:
    mode_unlimited_multiball_started:
        multiball_flash: 
            show_tokens:
                led: l_p1_unlimited_balls, l_p2_unlimited_balls
                color: red     
    timer_unlimited_multiball_complete:
        multiball_off:
            show_tokens:
                ledoff: l_p1_unlimited_balls, l_p2_unlimited_balls 
    player_timer_unlimited_multiball_variable:  #need to make sure this is the player variable
        P1_timer:
            show_tokens:
                txt: "{current_player.timer_unlimited_multiball_variable:0>1d}"
            key: timer1
        P2_timer:
            show_tokens:
                txt: "{current_player.timer_unlimited_multiball_variable:0>1d}"
            key: timer2
sound_player:
    timer_unlimited_multiball_tick: timer_pulse
