#config_version=5

mode:
    start_events: ball_starting 
    priority: 126
    events_when_started: enable_prevent_drain

#timed_switches:
#  game_cancel:
#    switch_tags: start
#    time: 5s
#    events_when_active: end_game
ball_saves:
    prevent_drain: #This is to have lives counter work and not have the ball drains count in the front trough
        enable_events: enable_prevent_drain
        disable_events: disable_prevent_drain
        auto_launch: false
        balls_to_save: -1 #unlimited
        debug: yes      
multiball_locks:  
    bd_trough_front:
        balls_to_lock: 2
        enable_events: enable_front_lock
        disable_events: disable_front_lock  
        lock_devices: bd_trough_front
        balls_to_replace: 0 #A value of 0 means the lock will never replace balls to the playfield from the default source (bd_trough_front), and -1 means it will always replace balls
        locked_ball_counting_strategy: physical_only
    bd_trough_back:
        balls_to_lock: 2
        enable_events: enable_back_lock  
        disable_events: disable_back_lock 
        lock_devices: bd_trough_back
        balls_to_replace: 0 #A value of 0 means the lock will never replace balls to the playfield from the default source (bd_trough_front), and -1 means it will always replace balls
        locked_ball_counting_strategy: physical_only 
       
shots:
#Player 1 side
    p1_r_drain_shot:
        switch: s_p1_r_drain
#Player 2 side
    p2_r_drain_shot:
        switch: s_p2_r_drain

show_player:
    mode_base_started: 
        base_gi:
            speed: 1
    s_p1_launcher_active:
        release:
            loops: 8
            show_tokens:
                led: l_p2_release
                color: tt_green  
    s_p2_launcher_active:
        release:
            loops: 8
            show_tokens:
                led: l_p1_release
                color: tt_green     
sound_player:  
#Player1
    balldevice_bd_launcher_back_ejecting_ball: explosion           
#Player2
    balldevice_bd_launcher_front_ejecting_ball: explosion     
