#config_version=5
#this mode is to make only the back trough launch 1 ball at the beginning of the mode and prevent the front trough from launching

mode:
    start_events: carousel_single_player_selected #changed from ball_starting so that the carousel starts with ball starting
    stop_events: balldevice_bd_launcher_front_ball_eject_attempt #this will shut down the mode after the 1st ball is launched
queue_relay_player: #this is to make the forward ball trough not send out the first ball
    balldevice_bd_trough_front_ball_eject_attempt:
        post: front_trough_waiting
        wait_for: s_p1_trough4_active
