#config_version=5
#this mode is a branch of the "base" mode for a double player game

mode:
    start_events: carousel_double_player_selected #changed from ball_starting so that the carousel starts with ball starting
    priority: 148
event_player:
    mode_double_player_started:
      - enable_p1_flipper
      - enable_double_player
      - enable_prevent_drain       
    mode_unlimited_multiball_started: 
      - enable_p1_flipper
      - enable_double_player
    logicblock_lives_front_counter_complete{device.counters.lives_back_counter.value==0}: round1end
    logicblock_lives_back_counter_complete{device.counters.lives_front_counter.value==0}: round1end
counters:
    lives_front_counter:
        count_events: s_p1_trough4_active       
        starting_count: 3
        count_interval: 1
        direction: down
        count_complete_value: 0
        reset_on_complete: false
        control_events:
          - event: logicblock_p1_hunter_group_count_complete
            action: add
            value: 1            
        disable_events: p1_disap_t_roll_hit, mode_single_player_started 
        enable_events: mode_double_player_started, timer_p1_tunnel_multiball_complete{device.counters.lives_front_counter.value > 0}
        debug: true 
    lives_back_counter:
        count_events: s_p2_trough4_active
        starting_count: 3
        count_interval: 1
        direction: down
        count_complete_value: 0          
        reset_on_complete: false
        control_events:
          - event: logicblock_p2_hunter_group_count_complete
            action: add
            value: 1    
        disable_events: p2_disap_t_roll_hit, mode_single_player_started 
        enable_events: mode_double_player_started, timer_p2_tunnel_multiball_complete{device.counters.lives_back_counter.value > 0} 
    p1_hunter_group_count:
        count_events: p1_hunter_shot_group_complete
        events_when_hit: p1_hunter_group_done
        starting_count: 0
        direction: up
        persist_state: true 
        count_complete_value: 3
        reset_on_complete: true
        disable_on_complete: false
        disable_events: mode_single_player_started, mode_colab_started
        multiple_hit_window: 500ms               
    p2_hunter_group_count:
        count_events: p2_hunter_shot_group_complete
        events_when_hit: p2_hunter_group_done
        starting_count: 0
        direction: up
        persist_state: true 
        count_complete_value: 3
        reset_on_complete: true
        disable_on_complete: false
        multiple_hit_window: 500ms
        disable_events: mode_single_player_started, mode_colab_started        

slide_player:
  mode_double_player_started:
    joust_monitor:
      target: monitor
 
slides:
  joust_monitor:
    widgets:
      - type: image
        image: joust_logo_sm
        anchor_x: center
        anchor_y: top
        y: 768
      - type: text
        text: DUAL PLAY
        font_name: joust
        font_size: 40
        color: red
        anchor_x: center
        anchor_y: top
        y: 555
      - type: text
        font_name: joust
        text: PLAYER 2
        y: 410
        x: 340
        font_size: 70
        color: 0189FF
        anchor_x: center
        anchor_y: bottom          
      - type: text
        font_name: joust
        text: (p2_score)
        number_grouping: true
        y: 280
        x: 340
        min_digits: 2
        font_size: 95
        color: 0189FF
        anchor_x: center
        anchor_y: bottom 
      - type: text
        font_name: joust
        text: EGG BONUS (p2_egg_bonus)
        y: 180
        x: 340
        min_digits: 2
        font_size: 54 
        color: 0189FF
        anchor_x: center
        anchor_y: bottom 
#player1
      - type: text
        font_name: joust
        text: PLAYER 1
        y: 410
        x: right-340
        font_size: 70
        color: yellow
        anchor_x: center
        anchor_y: bottom  
      - type: text
        text: (p1_score)
        font_name: joust
        number_grouping: true
        y: 280
        x: right-340
        min_digits: 2
        font_size: 95
        color: yellow
        anchor_x: center
        anchor_y: bottom 
      - type: text
        font_name: joust
        text: EGG BONUS (p1_egg_bonus) 
        y: 180
        x: right-340
        min_digits: 2
        font_size: 54
        color: yellow
        anchor_x: center
        anchor_y: bottom 
      - type: text
        font_name: joust
        text: MULTIBALL TIME (timer_unlimited_multiball_variable) 
        y: 90
        min_digits: 2
        font_size: 54
        color: red
        anchor_x: center
        anchor_y: bottom
        opacity: 0
        animations:
          mode_unlimited_multiball_started:                   # animation trigger event
            - property: opacity         # second step in the animation (starts with a hyphen)
              value: 1
              duration: 0s
      - type: image
        image: multiball
        anchor_x: center
        anchor_y: bottom
        y: 5
        opacity: 0 
        animations:
          mode_round1end_started:                   # animation trigger event
            - property: opacity         # name of the widget property we're animating
              value: 1                  # target value of that property for this step
              duration: 1s             # duration for this step (how long it takes to get there)
            - property: opacity         # second step in the animation (starts with a hyphen)
              value: 0
              duration: 1s
              repeat: true 
          mode_unlimited_multiball_started:                   # animation trigger event
            - property: opacity         # second step in the animation (starts with a hyphen)
              value: 0
              duration: 0s
show_player:
    player_p1_score:
        P1_score:
            show_tokens:
                txt: "{current_player.p1_score:0>1d}"
            key: p1score
    player_p2_score:
        P2_score:
            show_tokens:
                txt: "{current_player.p2_score:0>1d}"
            key: p2score
    player_lives_front_count: #need to make sure this is the player variable
        P1_lives:
            show_tokens:
                txt: "{current_player.lives_front_count:0>1d}"
            key: p1lives
    player_timer_unlimited_multiball_variable{value>0}:  #need to make sure this is the player variable
        P1_timer:
            show_tokens:
                txt: "{current_player.timer_unlimited_multiball_variable:0>1d}"
            key: timer1
        P2_timer:
            show_tokens:
                txt: "{current_player.timer_unlimited_multiball_variable:0>1d}"
            key: timer2
    player_lives_back_count:
        P2_lives:
            show_tokens:
                txt: "{current_player.lives_back_count:0>1d}"
            key: p2lives

variable_player:
 #Player 1 Side     
    logicblock_lives_front_counter_updated:
        lives_front_count:
           int: value
           action: set           
 #Player 2 Side     
    logicblock_lives_back_counter_updated:
        lives_back_count:
           int: value
           action: set        

sound_player:
    mode_double_player_started: 
      player_start:
         action: play   
 
