#config_version=5
mode:
  start_events: ball_starting
  stop_events: carousel_item_selected
  code: mpf.modes.carousel.code.carousel.Carousel
  use_wait_queue: true
  #game_mode: false
mode_settings:
  selectable_items: double_player, co-op, single_player
  select_item_events: s_p1_r_flipper_button_inactive, s_1p_start_button_inactive
  next_item_events: s_p1_l_flipper_button_inactive
  previous_item_events: s_p2_l_flipper_button_inactive
  block_events: flipper_cancel #what is this - check this may need to be same as select_item_events
  release_events: both_flippers_inactive
event_player:
  select_double_player: mode_double_player_start 
  select_co-op: mode_co-op_start 
  select_single_player: mode_single_player_start

slide_player:
  mode_carousel_started: 
    carousel:
      target: monitor
#  carousel_double_player_highlighted: select_double_player
#  carousel_co-op_highlighted: select_co-op
#  carousel_single_player_highlighted: select_single_player
 
slides:
  carousel:
      widgets:
      - type: image
        image: joust_logo_sm
        anchor_x: center
        anchor_y: top
        x: 640
        y: 768
      - type: text
        text: <- PLAYER 1 PRESS LEFT FLIPPER TO SELECT
        font_name: joust
        font_size: 35
        color: white
        anchor_x: center
        anchor_y: top
        x: 640
        y: 105
        animations:
          show_slide:                   # animation trigger event
            - property: opacity         # name of the widget property we're animating
              value: 0                  # target value of that property for this step
              duration: 2s             # duration for this step (how long it takes to get there)
            - property: opacity         # second step in the animation (starts with a hyphen)
              value: 1
              duration: 2s
              repeat: true    
      - type: image
        image: select_2pvs
        anchor_x: left
        anchor_y: bottom
        x: 0
        y: 0  
        animations:
          carousel_double_player_highlighted:
            - property: y         # name of the widget property we're animating
              value: 0                 # target value of that property for this step
              duration: 0s
          carousel_co-op_highlighted:                 # animation trigger event
            - property: y         # name of the widget property we're animating
              value: 768                  # target value of that property for this step
              duration: 0s             # duration for this step (how long it takes to get there) 
          carousel_single_player_highlighted:
            - property: y         # name of the widget property we're animating
              value: 768                 # target value of that property for this step
              duration: 0s
      - type: image
        image: select_2pco-op
        anchor_x: left
        anchor_y: bottom
        x: 0
        y: 768  
        animations:
          carousel_double_player_highlighted:
            - property: y         # name of the widget property we're animating
              value: 768                 # target value of that property for this step
              duration: 0s
          carousel_co-op_highlighted:                 # animation trigger event
            - property: y         # name of the widget property we're animating
              value: 0                  # target value of that property for this step
              duration: 0s             # duration for this step (how long it takes to get there) 
          carousel_single_player_highlighted:
            - property: y         # name of the widget property we're animating
              value: 768                 # target value of that property for this step
              duration: 0s
      - type: image
        image: select_single
        anchor_x: left
        anchor_y: bottom
        x: 0
        y: 768 
        animations:
          carousel_double_player_highlighted:
            - property: y         # name of the widget property we're animating
              value: 768                 # target value of that property for this step
              duration: 0s
          carousel_co-op_highlighted:                 # animation trigger event
            - property: y         # name of the widget property we're animating
              value: 768                  # target value of that property for this step
              duration: 0s             # duration for this step (how long it takes to get there) 
          carousel_single_player_highlighted:
            - property: y         # name of the widget property we're animating
              value: 0                 # target value of that property for this step
              duration: 0s
      - type: text
        text: PLAYER 1 PRESS RIGHT FLIPPER TO START ->
        font_name: joust
        number_grouping: true
        min_digits: 2
        font_size: 35
        color: yellow
        anchor_x: center
        anchor_y: bottom 
        x: 640
        y: 12  
        animations:
          show_slide:                   # animation trigger event
            - property: opacity         # name of the widget property we're animating
              value: 1                  # target value of that property for this step
              duration: 2s             # duration for this step (how long it takes to get there)
            - property: opacity         # second step in the animation (starts with a hyphen)
              value: 0
              duration: 2s
              repeat: true              # added to the final step, tells this animation to repeat (loop)   

show_player:
    carousel_double_player_highlighted:
        double_player_vs:
            action: play
        single_player:
            action: stop
        P2_score:
            show_tokens:
                txt: "2PLAYER"
    carousel_co-op_highlighted:
        double_player_vs:
            action: stop
        double_player_co-op:
            action: play
        P2_score:
            show_tokens:
                txt: "-CO-OP-"
    carousel_single_player_highlighted:
        double_player_co-op:
            action: stop
        single_player:
            action: play
        P2_score:
            show_tokens:
                txt: "-------"
shows:
    double_player_vs:
      - duration: 3  
        segment_displays:
         neoSeg0:
            text: " DUAL "
            transition:
               type: push
               direction: left   
      - duration: 2  
        segment_displays:
         neoSeg0:
            text: "  PRESS"
            transition:
               type: push
               direction: left
      - duration: 2  
        segment_displays:
         neoSeg0:
            text: " RIGHT "
            transition:
               type: push
               direction: left
      - duration: 1  
        segment_displays:
         neoSeg0:
            text: "FLIPPER"
            transition:
               type: push
               direction: left                               
      - duration: 1  
        segment_displays:
         neoSeg0:
            text: "   BUTTON"
            transition:
               type: push
               direction: left
      - duration: .5  
        segment_displays:
         neoSeg0:
            text: "   for  "
            transition:
               type: push
               direction: left
      - duration: 3  
        segment_displays:
         neoSeg0:
            text: "2PLAYER"
            transition:
               type: push
               direction: left      
      - duration: 2  
        segment_displays:
         neoSeg0:
            text: " JOUST "
            transition:
               type: push
               direction: left
      - duration: .5  
        segment_displays:
         neoSeg0:
            text: "  or  "
            transition:
               type: push
               direction: left
      - duration: 2  
        segment_displays:
         neoSeg0:
            text: "  PRESS"
            transition:
               type: push
               direction: left
      - duration: 2  
        segment_displays:
         neoSeg0:
            text: " LEFT "
            transition:
               type: push
               direction: left
      - duration: 1  
        segment_displays:
         neoSeg0:
            text: "FLIPPER"
            transition:
               type: push
               direction: left                               
      - duration: 1  
        segment_displays:
         neoSeg0:
            text: " BUTTON"
            transition:
               type: push
               direction: left
      - duration: .5  
        segment_displays:
         neoSeg0:
            text: "   to  "
            transition:
               type: push
               direction: left
      - duration: 2  
        segment_displays:
         neoSeg0:
            text: " SELECT"
            transition:
               type: push
               direction: left 
      - duration: .5  
        segment_displays:
         neoSeg0:
            text: "  or  "
            transition:
               type: push
               direction: left                          
    double_player_co-op:
      - duration: 3  
        segment_displays:
         neoSeg0:
            text: "-CO-OP-"
            transition:
               type: push
               direction: left
      - duration: 2  
        segment_displays:
         neoSeg0:
            text: "  PRESS"
            transition:
               type: push
               direction: left
      - duration: 2  
        segment_displays:
         neoSeg0:
            text: " RIGHT "
            transition:
               type: push
               direction: left
      - duration: 1  
        segment_displays:
         neoSeg0:
            text: "FLIPPER"
            transition:
               type: push
               direction: left                               
      - duration: 1  
        segment_displays:
         neoSeg0:
            text: " BUTTON"
            transition:
               type: push
               direction: left
      - duration: .5  
        segment_displays:
         neoSeg0:
            text: "   for  "
            transition:
               type: push
               direction: left
      - duration: 3  
        segment_displays:
         neoSeg0:
            text: "-CO-OP-"
            transition:
               type: push
               direction: left
      - duration: .5  
        segment_displays:
         neoSeg0:
            text: "  or  "
            transition:
               type: push
               direction: left
      - duration: 2  
        segment_displays:
         neoSeg0:
            text: "  PRESS"
            transition:
               type: push
               direction: left
      - duration: 2  
        segment_displays:
         neoSeg0:
            text: " LEFT "
            transition:
               type: push
               direction: left
      - duration: 1  
        segment_displays:
         neoSeg0:
            text: "FLIPPER"
            transition:
               type: push
               direction: left                               
      - duration: 1  
        segment_displays:
         neoSeg0:
            text: " BUTTON"
            transition:
               type: push
               direction: left
      - duration: .5  
        segment_displays:
         neoSeg0:
            text: "   to  "
            transition:
               type: push
               direction: left
      - duration: 2  
        segment_displays:
         neoSeg0:
            text: " SELECT"
            transition:
               type: push
               direction: left 
      - duration: .5  
        segment_displays:
         neoSeg0:
            text: "  or  "
            transition:
               type: push
               direction: left           
    single_player:
      - duration: 3  
        segment_displays:
         neoSeg0:
            text: " SINGLE"
            transition:
               type: push
               direction: left
      - duration: 2  
        segment_displays:
         neoSeg0:
            text: "  PRESS"
            transition:
               type: push
               direction: left
      - duration: 2  
        segment_displays:
         neoSeg0:
            text: " RIGHT "
            transition:
               type: push
               direction: left
      - duration: 1  
        segment_displays:
         neoSeg0:
            text: "FLIPPER"
            transition:
               type: push
               direction: left                               
      - duration: 1  
        segment_displays:
         neoSeg0:
            text: " BUTTON"
            transition:
               type: push
               direction: left
      - duration: .5  
        segment_displays:
         neoSeg0:
            text: "   to  "
            transition:
               type: push
               direction: left
      - duration: 2  
        segment_displays:
         neoSeg0:
            text: " JOUST "
            transition:
               type: push
               direction: left
      - duration: .5  
        segment_displays:
         neoSeg0:
            text: "  or  "
            transition:
               type: push
               direction: left
      - duration: 2  
        segment_displays:
         neoSeg0:
            text: "  PRESS"
            transition:
               type: push
               direction: left
      - duration: 2  
        segment_displays:
         neoSeg0:
            text: " LEFT "
            transition:
               type: push
               direction: left
      - duration: 1  
        segment_displays:
         neoSeg0:
            text: "FLIPPER"
            transition:
               type: push
               direction: left                               
      - duration: 1  
        segment_displays:
         neoSeg0:
            text: " BUTTON"
            transition:
               type: push
               direction: left
      - duration: .5  
        segment_displays:
         neoSeg0:
            text: "   to  "
            transition:
               type: push
               direction: left
      - duration: 2  
        segment_displays:
         neoSeg0:
            text: " SELECT"
            transition:
               type: push
               direction: left 
      - duration: .5  
        segment_displays:
         neoSeg0:
            text: "  or  "
            transition:
               type: push
               direction: left           
sound_player:
    mode_carousel_started: drain_rollover
