#config_version=5
mode:
  start_events: ball_starting #possibly start this with the second hidden trough switch active
  stop_events: round1end #timer_p1_tunnel_multiball_complete, timer_p2_tunnel_multiball_complete
  priority: 180

event_player:
    p1_disap_t_roll_hit: 
      - start_tunnel_multiball
      - eject_all #this is needed because for some reason after the first game - will not eject balls 
      - reset_target_tunnel
    p2_disap_t_roll_hit: 
      - start_tunnel_multiball
      - eject_all #this is needed because for some reason after the first game - will not eject balls 
      - reset_target_tunnel
    timer_p1_tunnel_multiball_complete: end_tunnel_multiball
    timer_p2_tunnel_multiball_complete: end_tunnel_multiball
    
timers:
    p1_tunnel_multiball: #this timer is for preventing drains for p1 when they initiate the multiball
        start_value: 16
        end_value: 0
        direction: down
        control_events:
            - event: p1_disap_t_roll_hit
              action: restart
    p2_tunnel_multiball: #this timer is for preventing drains for p1 when they initiate the multiball
        start_value: 16
        end_value: 0
        direction: down
        control_events:
            - event: p2_disap_t_roll_hit
              action: restart
    tunnel_multiball:
        start_value: 16
        end_value: -1
        direction: down
        control_events:
            - event: start_tunnel_multiball
              action: restart
multiballs:
    p1_tunnel_multiball_front:
        ball_count: 1
        ball_count_type: add
        enable_events: player_shot_p1_disap_t_2, player_shot_p2_disap_t_2
        start_events: start_tunnel_multiball
        stop_events: timer_p1_tunnel_multiball_complete, timer_p2_tunnel_multiball_complete, round1end
        ball_locks: bd_trough_front
        source_playfield: playfield
        shoot_again: 15s
    p2_tunnel_multiball_back:
        ball_count: 1
        ball_count_type: add
        enable_events: player_shot_p2_disap_t_2, player_shot_p1_disap_t_2
        start_events: start_tunnel_multiball
        stop_events: timer_p1_tunnel_multiball_complete, timer_p2_tunnel_multiball_complete, round1end
        ball_locks: bd_trough_back
        source_playfield: playfield
        shoot_again: 15s     
multiball_locks:  
    trough_front1:
        balls_to_lock: 1
        enable_events: end_tunnel_multiball
        disable_events: round1end, start_tunnel_multiball  
        lock_devices: bd_trough_front
        balls_to_replace: 0 #A value of 0 means the lock will never replace balls to the playfield from the default source (bd_trough_front), and -1 means it will always replace balls
        locked_ball_counting_strategy: physical_only
    trough_back1:
        balls_to_lock: 1
        enable_events: end_tunnel_multiball
        disable_events: round1end, start_tunnel_multiball  
        lock_devices: bd_trough_back
        balls_to_replace: 0 #A value of 0 means the lock will never replace balls to the playfield from the default source (bd_trough_front), and -1 means it will always replace balls
        locked_ball_counting_strategy: physical_only

variable_player:
    timer_tunnel_multiball_tick:
        timer_tunnel_multiball_variable:
            int: ticks
            action: set
sound_player:
    timer_tunnel_multiball_tick: timer_pulse
shows:
    tunnel_multiball_flash:
        - duration: 200ms
          lights:
              (led): (color)
        - duration: 100ms
          lights:
              (led): off    
    tunnel_multiball_off:
        - time: 0
          lights:
              (led): tt_white
              (ledoff): black
show_player:
    p1_disap_t_roll_hit:
        tunnel_multiball_flash: 
            show_tokens:
                led: l_p1_unlimited_balls, l_p2_unlimited_balls
                color: red
    timer_tunnel_multiball_complete:
        tunnel_multiball_off:
            show_tokens:
                ledoff: l_p1_unlimited_balls, l_p2_unlimited_balls 
    player_timer_tunnel_multiball_variable:
        P1_timer:
            show_tokens:
                txt: "{current_player.timer_tunnel_multiball_variable:0>1d}"
            key: timer1
        P2_timer:
            show_tokens:
                txt: "{current_player.timer_tunnel_multiball_variable:0>1d}"
            key: timer2            
